sonar.projectKey=ankitkc1_sit753_hd
sonar.organization=ankitkc1
sonar.projectName=SIT753 Portfolio Blog CMS
sonar.projectVersion=1.0

sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.tests=tests

sonar.inclusions=**/*.js
sonar.exclusions=node_modules/**,coverage/**,public/**,views/**,data/**,**/*.test.js,Jenkinsfile,Dockerfile

sonar.test.inclusions=tests/**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8